[images]
remote_images = [
  "https://images.unsplash.com/*",
  "https://upload.wikimedia.org/wikipedia/commons/*",
  "https://de.artsdot.com/*",
  "https://www.ackroydandharvey.com/*",
  "https://www.moma.org/*",
  "https://www.arttrav.com/*",
  "https://meine.rs/*",
  "https://malteroemer.com",
  "www.moebelmuseumwien.at",
  "images.e-flux-systems.com",
  "www.klaus-guendchen.de",
]
